# PWA Icon Generator Script
# This script helps you create PWA icons from your profile photo

echo "📱 PWA Icon Generator for Aakash Portfolio"
echo "==========================================="
echo ""
echo "To create PWA icons, you need to:"
echo ""
echo "1. Use an online tool like:"
echo "   - https://realfavicongenerator.net/"
echo "   - https://www.pwabuilder.com/imageGenerator"
echo "   - https://favicon.io/favicon-converter/"
echo ""
echo "2. Upload your profile photo (aakash-1.png)"
echo ""
echo "3. Generate these sizes:"
echo "   - 72x72"
echo "   - 96x96"
echo "   - 128x128"
echo "   - 144x144"
echo "   - 152x152"
echo "   - 192x192"
echo "   - 384x384"
echo "   - 512x512"
echo ""
echo "4. Download and save them to: assets/icons/"
echo ""
echo "5. Or use ImageMagick (if installed):"
echo "   for size in 72 96 128 144 152 192 384 512; do"
echo "     convert assets/png/aakash-1.png -resize \${size}x\${size} assets/icons/icon-\${size}x\${size}.png"
echo "   done"
echo ""
echo "✅ Icons are ready to use!"
